swagger: '2.0'
basePath: /
paths:
  /api/persons:
    get:
      responses:
        '200':
          description: Success
      operationId: get_persons_resource
      tags:
        - UdaConnect
    post:
      responses:
        '200':
          description: Success
      operationId: post_persons_resource
      tags:
        - UdaConnect
  /api/persons/{person_id}:
    parameters:
      - in: path
        description: Unique ID for a given Person
        name: person_id
        required: true
        type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_person_resource
      tags:
        - UdaConnect
info:
  title: UdaConnect Person API
  version: 0.1.0
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: UdaConnect
    description: Persons api
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
